WebApplication2/WebApplication2/Controllers/DefaultController.cs
using System.Linq;
using System.Web.Mvc;
using Stormpath.AspNet.WebApi;
using WebApplication.Service.Services.Base;
using WebApplication2.Domain.Entities;

namespace WebApplication2.Controllers
{
    [Authorize]
    [StormpathGroupsRequired("admin")]
    [StormpathGroupsRequired("user")]
    public class DefaultController : Controller
    {
        private IPhoneBookService _phoneBookService = null;

        public DefaultController(IPhoneBookService phoneBookService)
        {
            _phoneBookService = phoneBookService;
        }

        public ActionResult Phones()
        {
            var phones = _phoneBookService.GetPhoneBooks()
                .Select(x => new PhoneBook
                {
                    Id = x.Id,
                    Fio = x.Fio,
                    IsDeleted = x.IsDeleted,
                    PhoneNumber = x.PhoneNumber,
                    Pochtamt = x.Pochtamt
                }).ToArray();

            return View(phones);
        }

        [HttpGet]
        public ActionResult DeletePhone(int id)
        {
            _phoneBookService.DeletePhone(id);
            return RedirectToAction("Phones");
        }

        [HttpGet]
        public ActionResult RestorePhone(int id)
        {
            _phoneBookService.RestorePhone(id);
            return RedirectToAction("Phones");
        }

        [HttpGet]
        public ActionResult AddPhone()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddPhone(PhoneBook phone)
        {
            _phoneBookService.AddPhone(new PhoneBook
            {
                Fio = phone.Fio,
                Id = phone.Id,
                IsDeleted = false,
                PhoneNumber = phone.PhoneNumber,
                Pochtamt = phone.Pochtamt
            });
            return RedirectToAction("Phones");
        }

        [HttpGet]
        public ActionResult EditPhone(int id)
        {
            var phone = _phoneBookService.GetPhoneBooks()
                .FirstOrDefault(x => x.Id == id);

            return View(new PhoneBook
            {
                Id = phone.Id,
                Fio = phone.Fio,
                IsDeleted = phone.IsDeleted,
                PhoneNumber = phone.PhoneNumber,
                Pochtamt = phone.Pochtamt
            });
        }

        [HttpPost]
        public ActionResult EditPhone(PhoneBook phone)
        {
            _phoneBookService.EditPhone(new PhoneBook
            {
                Fio = phone.Fio,
                Id = phone.Id,
                IsDeleted = false,
                PhoneNumber = phone.PhoneNumber,
                Pochtamt = phone.Pochtamt
            });
            return RedirectToAction("Phones");
        }
    }
}

WebApplication2/WebApplication2/Controllers/ScriptController.cs
using System.Linq;
using System.Web.Mvc;
using Stormpath.AspNet.WebApi;
using WebApplication.Service.Services.Base;
using WebApplication2.Domain.Entities;

namespace WebApplication2.Controllers
{
    [Authorize]
    [StormpathGroupsRequired("admin")]
    [StormpathGroupsRequired("user")]
    public class ScriptController : Controller
    {
        private IScriptServices _scriptServices = null;

        public ScriptController(IScriptServices scriptServices)
        {
            _scriptServices = scriptServices;
        }

        [Authorize]
        public ActionResult Scripts()
        {
            var script = _scriptServices.GetScripts()
                .Select(x => new Script
                {
                    Id = x.Id,
                    Scripts = x.Scripts,
                    Description = x.Description,
                    IsDeleted = x.IsDeleted
                }).ToArray();
            return View(script);
        }


        [HttpGet]
        public ActionResult DeleteScript(int id)
        {
            _scriptServices.DeleteScript(id);
            return RedirectToAction("Scripts");
        }

        [HttpGet]
        public ActionResult RestoreScript(int id)
        {
            _scriptServices.RestoreScript(id);
            return RedirectToAction("Scripts");
        }

        [Authorize]
        [HttpGet]
        public ActionResult AddScript()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddScript(Script script)
        {
            _scriptServices.AddScript(new Script
            {
                Id = script.Id,
                Scripts = script.Scripts,
                Description = script.Description,
                IsDeleted = false
            });
            return RedirectToAction("Scripts");
        }

        [HttpGet]
        public ActionResult EditScript(int id)
        {
            var script = _scriptServices.GetScripts()
                .FirstOrDefault(x => x.Id == id);

            return View(new Script
            {
                Id = script.Id,
                Scripts = script.Scripts,
                Description = script.Description,
                IsDeleted = script.IsDeleted
            });
        }

        [HttpPost]
        public ActionResult EditScript(Script script)
        {
            _scriptServices.EditScript(new Script
            {
                Id = script.Id,
                Scripts = script.Scripts,
                Description = script.Description,
                IsDeleted = false
            });
            return RedirectToAction("Scripts");
        }

        //[HttpGet]
        //public ActionResult DetailsScript(int id)
        //{
        //    var script = _scriptServices.GetScripts()
        //        .FirstOrDefault(x => x.Id == id);
        //    if (script != null)
        //    {
        //        return PartialView(script);
        //    }
        //    return HttpNotFound();

        //}
    }
}

WebApplication2/WebApplication2/Views/Shared/_AuthenticationLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title - EasyWork</title>

    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="https://use.fontawesome.com/e6d1965c0f.js"></script>
    
    <script src="https://use.fontawesome.com/e6d1965c0f.js"></script>
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>
<body>

<div>
        @RenderBody()
</div>
    
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

WebApplication2/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - EasyWork</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3"></script>
</head>
<body>
    <div id="wrapper">
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a>Easy Work</a>
                </li>
                <li>
                    @Html.ActionLink("Решения и проблемы", "ProblemDecision", "ProblemDecision")
                </li>
                <li>
                    @Html.ActionLink("Телефонный справочник", "Phones", "Default")
                </li>
                <li>
                    @Html.ActionLink("Скрипты", "Scripts", "Script")
                </li>
                <hr />
                <li>
                    <span>Хаюшки,</span><span>@Context.User.Identity.Name</span>
                </li>
                @*<li>
                    <a onclick="document.getElementById('logout_form').submit();" style="cursor: pointer;">Порошок уходи</a>
                </li>*@
            </ul>
            @*@if (Context.User.Identity.IsAuthenticated)
            {
                <form action="/logout" method="post" id="logout_form">
                    <ul class="sidebar-nav">
                        <li>
                            <p class="navbar-text">
                                Хаюшки! <b>@Context.User.Identity.Name</b>
                            </p>
                        </li>
                        <li>
                            
                        </li>
                    </ul>
                </form>
            }*@

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        @RenderSection("scpitps", required:false)
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - D.A.SHIMANOV</p>
        </footer>*@
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>